# Generated by Django 2.2.10 on 2024-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_link',
        ),
    ]
